In [9]:
##Instalación de librerias
system("pip install -q google-colab")
system("python - <<EOF
from google.colab import drive
drive.mount('/content/drive')
EOF")
install.packages("readxl")
library(readxl)
install.packages("openxlsx")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [10]:
##Se Lee el archivo Calendario.xlsx
df_calendario <- read_excel("/content/Calendario.xlsx", sheet = "Calendario")
df_calendario$Fecha <- as.Date(df_calendario$Fecha)

#Se realiza una transformación para traducir de ingles a español el nombre de los meses
meses <- c(
"enero","febrero","marzo","abril","mayo","junio",
"julio","agosto","septiembre","octubre","noviembre","diciembre"
)

df_calendario$Numero_Mes <- as.numeric(format(df_calendario$Fecha,"%m"))
df_calendario$Nombre_Mes <- meses[df_calendario$Numero_Mes]
df_calendario$Anio <- format(df_calendario$Fecha,"%Y")
print(paste("Cantidad de registros de Calendario:", nrow(df_calendario)))
head(df_calendario)

[1] "Cantidad de registros de Calendario: 1095"

  Fecha      Numero_Mes Nombre_Mes Anio
1 2017-01-01 1          enero      2017
2 2017-01-02 1          enero      2017
3 2017-01-03 1          enero      2017
4 2017-01-04 1          enero      2017
5 2017-01-05 1          enero      2017
6 2017-01-06 1          enero      2017

In [11]:
##Se Lee el archivo Cliente.xlsx
df_Clientes1 <- read_excel("/content/Cliente.xlsx", sheet = "Clientes1")
df_Clientes2 <- read_excel("/content/Cliente.xlsx", sheet = "Clientes2")
df_Clientes3 <- read_excel("/content/Cliente.xlsx", sheet = "Clientes3")

##Se realiza el join por IdCliente estre los data frame
df_clientes_tmp1 <- merge(df_Clientes1, df_Clientes2, by = "IdCliente")
df_clientes <- merge(df_clientes_tmp1, df_Clientes3, by = "IdCliente")

print(paste("Cantidad de registros de clientes:", nrow(df_clientes)))
head(df_clientes)

[1] "Cantidad de registros de clientes: 20"

  IdCliente NombreCli         FlagCarro Income
1 1         ALLEN, MICHAEL    1         10000
2 2         HASSALL, MARK     0         15000
3 3         PEOPLES, JOHN     0         17000
4 4         ARNDT, TORSTEN    0         10000
5 5         HIGGINBOTHAM, TOM 1         15000
6 6         POLAND, CAROLE    1         17000

In [12]:
##Se Lee el archivo Territorio.csv
df_territorio <- read.table(
  "/content/Territorio.csv",
  header = TRUE,
  sep = ";",
  fill = TRUE,
  quote = "\"",
  fileEncoding = "latin1"
)

print(paste("Cantidad de registros de Territorio:", nrow(df_territorio)))
head(df_territorio)

[1] "Cantidad de registros de Territorio: 3"

  IdTerritorio Lat         Lon         Place
1 10           -12,025827  -77,267978  Lima, Perú
2 11           -8,116666   -79,054635  Trujillo, Perú
3 12           -7,160549   -78,539222  Cajamarca, Perú

In [17]:
##Se Lee el archivo Vendedor.xlsx
df_Vendedor <- read_excel("/content/Vendedor.xlsx", sheet = "Vendedor")
print(paste("Cantidad de registros Total de Vendedor:", nrow(df_Vendedor)))
head(df_Vendedor)

[1] "Cantidad de registros Total de Vendedor: 5"

  IdVendedor Nombre    Apellido
1 1          Alejandro SANCHEZ
2 2          Raul      SARACHAGA
3 3          Rosario   PADILLA
4 4          July      TORRES
5 5          Brian     KOO

In [18]:
##Se Lee el archivo Productos.xlsx
df_Productos <- read_excel("/content/Productos.xlsx", sheet = "Prod")
print(paste("Cantidad de registros Total de Productos:", nrow(df_Productos)))
head(df_Productos)

[1] "Cantidad de registros Total de Productos: 11"

  IdProducto Name          cat
1 100        Product HHYDP beverages
2 101        Product RECZE condiments
3 102        Product IMEHJ meat/poultry
4 103        Product KSBRM beverages
5 104        Product EPEIM condiments
6 105        Product VAIIV beverages

In [15]:
##Se Leen los archivos de 2017.xlsx, 2018.xlsx y 2019.xlsx
df_data_2019 <- read_excel("/content/Data/2019.xlsx", sheet = "Data")
df_data_2018 <- read_excel("/content/Data/2018.xlsx", sheet = "Data")
df_data_2017 <- read_excel("/content/Data/2017.xlsx", sheet = "Data")

df_data <- rbind(df_data_2017, df_data_2018, df_data_2019)
df_data$Fecha <- as.Date(df_data$Fecha)
print(paste("Cantidad de registros Total de 3 años:", nrow(df_data)))
head(df_data)

[1] "Cantidad de registros Total de 3 años: 1617"

  OrdenId Fecha      IdTerr IdCliente IdProducto IdEmp Cantidad Valido
1 1001    2017-01-02 10     10        106        4      3       1
2 1003    2017-01-04 10     13        100        4      2       1
3 1004    2017-01-05 10     18        108        2      6       1
4 1009    2017-01-10 10      8        106        3      9       1
5 1012    2017-01-13 10     19        104        1     10       1
6 1013    2017-01-14 10      2        109        2      8       1
  PrecioUntario Costo
1 20            2
2 15            5
3 10            5
4 20            2
5 15            5
6 12            6

In [16]:
##exportar data frames a un excel
library(openxlsx)
write.xlsx(df_calendario, "/content/df_calendario.xlsx")
write.xlsx(df_clientes, "/content/df_clientes.xlsx")
write.xlsx(df_territorio, "/content/df_territorio.xlsx")
write.xlsx(df_Vendedor, "/content/df_Vendedor.xlsx")
write.xlsx(df_Productos, "/content/df_Productos.xlsx")
write.xlsx(df_data, "/content/df_data.xlsx")
#lista <- list(
#  Calendario = df_calendario,
#  Clientes = df_clientes,
#  Territorio = df_territorio,
#  Vendedor = df_Vendedor,
#  Productos = df_Productos,
#  Data = df_data
#)
#
#write.xlsx(lista, "/content/resultado.xlsx")